python finetune-chatglm.py \
    --base_model_path ../model/chatglm-6b \
    --dataset_path ../data/chatglm-tuning/chatglm-chat-all \
    --output_dir ../model/chatglm-tuning/chatglm-chat-all-0713-0 \
    --lora_rank 8 \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 2 \
    --max_steps 2000 \
    --save_steps 500 \
    --save_total_limit 5 \
    --learning_rate 1e-5 \
    --fp16 \
    --remove_unused_columns false \
    --logging_steps 20
