python finetune-chatglm.py \
    --base_model_path ../model/chatglm-6b \
    --dataset_path ../data/chatglm-tuning/chatglm-chat-all \
    --output_dir ../model/chatglm-tuning/chatglm-chat-all-0717-1 \
    --lora_rank 32 \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 2 \
    --num_train_epochs 10 \
    --save_strategy "steps" \
    --save_steps 500 \
    --save_total_limit 5 \
    --learning_rate 2e-5 \
    --fp16 \
    --remove_unused_columns false \
    --logging_steps 20 \
    --load_in_8bit False
